# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iaa_name', models.CharField(max_length=64, verbose_name='IAA Name')),
                ('start_date', models.DateField(verbose_name='Agreement Start Date')),
                ('end_date', models.DateField(verbose_name='Agreement End Date')),
            ],
        ),
    ]
