# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170523_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='iaa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iaa.IAA', verbose_name='IAA'),
        ),
    ]
