# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='effective_package_date',
            field=models.DateField(null=True, verbose_name='Package Effective Date'),
        ),
    ]
