# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_effective_package_date'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='effective_package_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='quota_memory_limit',
        ),
        migrations.CreateModel(
            name='PackageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Package Effective Start Date')),
                ('end_date', models.DateField(null=True, verbose_name='Package Effective End Date')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Package')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='QuotaHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_memory_limit', models.PositiveIntegerField(verbose_name='Quota Memory Limit (in GB)')),
                ('start_date', models.DateField(verbose_name='Quota Effective Start Date')),
                ('end_date', models.DateField(null=True, verbose_name='Quota Effective End Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
