# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='yearly_price',
            new_name='monthly_price',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='yearly_price_currency',
            new_name='monthly_price_currency',
        ),
    ]
